name: Trigger every 15 mins

on:
 #schedule:
    #- cron: '*/15 * * * *'  # Cron expression to trigger every 15 minutes

 workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
       - name: Set up Java 11
         uses: actions/setup-java@v4
         with:
            distribution: 'temurin'
            java-version: '11'
            
       - name: Checkout code
         uses: actions/checkout@v3
        
       - name: Set up Appium
         run: |
           npm install -g appium@2
           appium -v

       - name: Set up UIAutomator2
         run: |
          appium driver install uiautomator2
          
       - name: Start Appium server
         run: |
          appium &>/dev/null &

       - name: run tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
          api-level: 29
          script: |
                  mvn clean test
